export const brakeArticle = {
  path: '/articles/ev-carbon-ceramic-brakes-guide',
  url: 'https://evselects.com/articles/ev-carbon-ceramic-brakes-guide',
  title: 'เบรก EV ต้องใหญ่แค่ไหน ถึงจะคุ้ม?',
  subtitle: 'จานเรียบ เซาะร่อง เจาะรู หรือ Carbon Ceramic — เลือกจากงานที่เบรกต้องรับ',
  description: 'เลือกเบรก EV ให้คุ้ม: ขนาดจาน จานเรียบ เซาะร่อง เจาะรู Carbon Ceramic และ ENDLESS พร้อมเครื่องคำนวณพลังงานเบรก วิเคราะห์ทางลงเขาไทย และเช็กลิสต์ก่อนซื้อ',
  publishedAt: '2026-09-02',
  updatedAt: '2026-09-19',
  readTime: '25 นาที',
  cover: '/images/articles/porsche-pccb-carbon-ceramic-brakes.jpg',
  coverAlt: 'ภาพถ่าย Porsche PCCB คาลิเปอร์เหลืองทองและจาน Carbon Ceramic หลังล้อ Center Lock',
};

export const brakeSources = {
  porsche: { title: 'Porsche — PCCB explained และภาพปก', url: 'https://www.porsche.com/stories/innovation/porsche-ceramic-composite-brakes-pccb-explained/' },
  apUpgrade: { title: 'AP Racing — Disc Choice สำหรับชุดอัปเกรด', url: 'https://apracing.com/performance-upgrades/factory-big-brake-kits/disc-choice' },
  apRace: { title: 'AP Racing — Disc Choice สำหรับรถแข่ง', url: 'https://apracing.com/race-car/brake-discs/disc-choice' },
  apTemp: { title: 'AP Racing — Disc Temperatures: เนื้อจาน ผิวจาน และการวัด', url: 'https://apracing.com/race-car/brake-discs/disc-temperatures' },
  bremboSurface: { title: 'Brembo — เลือก Max หรือ Xtra: ร่อง รู และข้อแลกเปลี่ยน', url: "https://www.bremboparts.com/europe/en/support/car/how-to-choose-the-right-product/what's-the-best-choice-for-my-car-max-or-xtra-discs-93372" },
  prime: { title: 'Brembo — Prime brake discs และภาพจานเรียบ', url: 'https://www.bremboparts.com/europe/en/products/prime/brake-discs' },
  max: { title: 'Brembo — Max และภาพจานเซาะร่อง', url: 'https://www.bremboparts.com/europe/en/products/xtra/max-brake-discs' },
  xtra: { title: 'Brembo — Xtra และภาพจานเจาะรู', url: 'https://www.bremboparts.com/europe/en/products/xtra/xtra-brake-discs' },
  ccb: { title: 'Brembo — วัสดุ Carbon Ceramic และขอบเขตอุณหภูมิที่ผู้ผลิตอธิบาย', url: 'https://www.brembo.com/en/motorsport/50motorsport/innovation-carbon-ceramic-disc' },
  ccbWear: { title: 'Brembo — Carbon Ceramic: การใช้งานถนนกับสนาม', url: 'https://www.bremboparts.com/europe/en/products/upgrade/carbon-ceramic' },
  ceramicPad: { title: 'Brembo — Xtra Ceramic P65017NX: ตัวอย่างผ้าเซรามิกที่ห้ามใช้กับจาน CCB', url: 'https://www.bremboparts.com/america/en/catalogue/pad/P65017NX' },
  fluid: { title: 'Brembo — การเลือกน้ำมันเบรกให้ตรงข้อกำหนดรถ', url: 'https://asia.bremboparts.com/america/en/support/car/how-to-choose-the-right-product/which-is-the-right-brake-fluid-for-my-car-195105' },
  teslaBrakes: { title: 'Tesla Model 3 — คู่มือภาษาไทย: เบรกและ Regenerative Braking', url: 'https://www.tesla.com/ownersmanual/model3/th_th/GUID-3DFFB071-C0F6-474D-8A45-17BE1A006365.html' },
  teslaSize: { title: 'Tesla Model 3 — คู่มือภาษาไทย: ขนาดจานเบรก', url: 'https://www.tesla.com/ownersmanual/model3/th_th/GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html' },
  teslaService: { title: 'Tesla Thailand — การบำรุงรักษารถ', url: 'https://www.tesla.com/th_th/support/vehicle-maintenance' },
  plaid: { title: 'Tesla — Model S Plaid Track Package (ตลาด UAE) และภาพชุดเบรก', url: 'https://shop.tesla.com/en_ae/product/model-s-plaid-track-package' },
  inthanon: { title: 'ประชาสัมพันธ์จังหวัดเชียงใหม่ — สภาพเส้นทาง ทล.1009 จอมทอง–อินทนนท์', url: 'https://chiangmai.prd.go.th/th/content/category/detail/id/9/iid/227283' },
  thapBoek: { title: 'DASTA — เส้นทางหล่มเก่า–ภูทับเบิก ผ่าน ทล.2331', url: 'https://cbtthailand.dasta.or.th/webapp/relattraction/content/1118/' },
  evKit: { title: 'Brembo — EV Kit สำหรับการใช้งานเบรกของรถไฟฟ้า', url: 'https://www.brembo.com/en/solutions/for-your-car/ev-kit' },
  sss: { title: 'ENDLESS Japan — SSS', url: 'https://www.endless-sport.co.jp/products/brake_pad/SSS.html' },
  ssm: { title: 'ENDLESS Japan — SSM PLUS', url: 'https://www.endless-sport.co.jp/products/brake_pad/SSMPLUS.html' },
  mx72: { title: 'ENDLESS Japan — MX72', url: 'https://www.endless-sport.co.jp/products/brake_pad/MX72.html' },
  mx72Plus: { title: 'ENDLESS Japan — MX72 PLUS', url: 'https://www.endless-sport.co.jp/products/brake_pad/MX72PLUS.html' },
  endlessCaliper: { title: 'ENDLESS Japan — 6POT และภาพคาลิเปอร์', url: 'https://www.endless-sport.co.jp/products/brake_caliper/index_6POT.html' },
  endlessFitment: { title: 'ENDLESS Japan — ตารางรถสำหรับชุดคาลิเปอร์', url: 'https://www.endless-sport.co.jp/products/brake_caliper/car_list.html' },
  endlessCoating: { title: 'ENDLESS Japan — ข้อควรระวังสำหรับจานเคลือบกันสนิม', url: 'https://www.endless-sport.co.jp/products/brake_pad/caution_antiRust.html' },
  endlessCcm: { title: 'ENDLESS — ผ้าเบรกสำหรับจาน CCM', url: 'https://endless-brake.info/products/brake-pads/for-ccm-discs/' },
  projectMu: { title: 'Project μ Japan — TYPE PS', url: 'https://www.project-mu.co.jp/ja/product-info/type_ps' },
};
