export const brakeArticle = {
  path: '/articles/ev-carbon-ceramic-brakes-guide',
  url: 'https://evselects.com/articles/ev-carbon-ceramic-brakes-guide',
  title: 'Carbon Ceramic คุ้มไหม? ก่อนจ่ายหลักแสนอัปเกรดเบรก EV',
  subtitle: 'เสน่ห์ของเบรกระดับซูเปอร์คาร์ และความคุ้มค่าบน EV ที่ขับทุกวัน',
  description: 'Carbon Ceramic คุ้มกับ EV คันโปรดแค่ไหน? ชวนดูทั้งฟีลเบรก ฝุ่น ความสวย และค่าดูแล เทียบกับตัวเลือก Brembo และ ENDLESS พร้อมประสบการณ์จากเจ้าของ Model 3 Performance Highland',
  publishedAt: '2026-09-02',
  updatedAt: '2026-09-24',
  readTime: '30 นาที',
  cover: '/images/articles/pccb-carrera-s-dan-lindsay.jpg',
  coverAlt: 'จาน Carbon Ceramic PCCB และคาลิเปอร์สีเหลืองบน Porsche Carrera S รุ่น 997 ขณะถอดล้อ',
  coverWidth: 1280,
  coverHeight: 852,
  coverSource: 'https://commons.wikimedia.org/wiki/File:PCCB_Wiki_9949.jpg',
  coverAuthor: 'Dan Lindsay (Edgy01)',
  coverLicense: 'CC0 1.0',
  coverLicenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
};

export const brakeSources = {
  slottedPhoto: { title: 'Numobeer — ภาพจานเซาะร่อง (2016)', url: 'https://commons.wikimedia.org/wiki/File:Freno_a_disco_baffato.jpg' },
  amgPhoto: { title: 'Cheeni — ภาพเบรก Carbon Ceramic AMG ที่ Geneva Auto Show 2011', url: 'https://commons.wikimedia.org/wiki/File:Amg_carbon_ceramic_brake_geneva_auto_show_2011.JPG' },
  ccBySa4: { title: 'Creative Commons BY-SA 4.0 — เงื่อนไขใช้ภาพ', url: 'https://creativecommons.org/licenses/by-sa/4.0/' },
  ccBySa3: { title: 'Creative Commons BY-SA 3.0 — เงื่อนไขใช้ภาพ', url: 'https://creativecommons.org/licenses/by-sa/3.0/' },
  endlessM6: { title: 'ENDLESS Global — M6 / EC690 / RCP208–209', url: 'https://www.endless-sport.global/jp/products/caliper_a/150' },
  alvell6: { title: 'ENDLESS — ALVELL6 และรายการอุปกรณ์ในชุด', url: 'https://www.endless-sport.co.jp/products/brake_caliper/index_Alvel6.html' },
  alvellPrice: { title: 'ENDLESS — ราคา FIYIXGH40W 380×34 mm และรถที่รองรับ', url: 'https://www.endless-sport.co.jp/products/brake_caliper/BrakeCaliper_Carlist/toyota/TOYOTA_Alphard40.html' },
  fs6: { title: 'Project μ — FS6 พร้อมรายการอุปกรณ์และผ้ามาตรฐาน', url: 'https://www.project-mu.co.jp/ja/product-info/forged_sports_caliper_6pistons_fs6' },
  fs6Price: { title: 'Project μ — ตาราง Toyota / FS6-T127C 380×32 mm', url: 'https://www.project-mu.co.jp/matching/caliper/caliper_matching.files/sheet003.htm' },
  apKit: { title: 'AP Racing by Essex — ชุดหน้า 9561/380 mm ราคาและเงื่อนไขล้อ', url: 'https://www.essexparts.com/essex-designed-ap-racing-radi-cal-competition-brake-kit-front-cp9562380mm-tesla-model-3' },
  apDealer: { title: 'AP Racing — รายชื่อ Distributor รวม Essex', url: 'https://apracing.com/find-a-dealer' },
  apInstall: { title: 'Essex — คู่มือติดตั้ง Model 3 และคำเตือน off-road only หน้า 2', url: 'https://www.essexparts.com/storage/wysiwyg/20-99-00012.pdf' },
  bremboKit: { title: 'Brembo / Race Technologies — GT | M 1N1.9076A2 380×34 mm', url: 'https://www.racetechnologies.com/products/brembo-gt-m-front-brake-system-6-piston-caliper-2-piece-disc-18-model-3-awd-18-model-3-rwd-1' },
  bremboPartner: { title: 'Brembo — เอกสารปี 2012 ที่ระบุ Race Technologies เป็นคู่ค้าด้านการจำหน่าย', url: 'https://www.brembo.com/jp/ComunicatiStampa/2012/RaceReadybrakekits.pdf' },
  porsche: { title: 'Porsche — PCCB explained: เทคโนโลยีเบรกคาร์บอนเซรามิก', url: 'https://www.porsche.com/stories/innovation/porsche-ceramic-composite-brakes-pccb-explained/' },
  apUpgrade: { title: 'AP Racing — Disc Choice สำหรับชุดอัปเกรด', url: 'https://apracing.com/performance-upgrades/factory-big-brake-kits/disc-choice' },
  apRace: { title: 'AP Racing — Disc Choice สำหรับรถแข่ง', url: 'https://apracing.com/race-car/brake-discs/disc-choice' },
  apTemp: { title: 'AP Racing — Disc Temperatures: เนื้อจาน ผิวจาน และการวัด', url: 'https://apracing.com/race-car/brake-discs/disc-temperatures' },
  bremboSurface: { title: 'Brembo — เลือก Max หรือ Xtra: ร่อง รู และข้อแลกเปลี่ยน', url: "https://www.bremboparts.com/europe/en/support/car/how-to-choose-the-right-product/what's-the-best-choice-for-my-car-max-or-xtra-discs-93372" },
  prime: { title: 'Brembo — Prime brake discs และจานผิวเรียบ', url: 'https://www.bremboparts.com/europe/en/products/prime/brake-discs' },
  max: { title: 'Brembo — Max และจานเซาะร่อง', url: 'https://www.bremboparts.com/europe/en/products/xtra/max-brake-discs' },
  xtra: { title: 'Brembo — Xtra และจานเจาะรู', url: 'https://www.bremboparts.com/europe/en/products/xtra/xtra-brake-discs' },
  ccb: { title: 'Brembo — วัสดุ Carbon Ceramic และขอบเขตอุณหภูมิที่ผู้ผลิตอธิบาย', url: 'https://www.brembo.com/en/motorsport/50motorsport/innovation-carbon-ceramic-disc' },
  ccbWear: { title: 'Brembo — Carbon Ceramic: การใช้งานถนนกับสนาม', url: 'https://www.bremboparts.com/europe/en/products/upgrade/carbon-ceramic' },
  ceramicPad: { title: 'Brembo — Xtra Ceramic P65017NX: ตัวอย่างผ้าเซรามิกที่ห้ามใช้กับจาน CCB', url: 'https://www.bremboparts.com/america/en/catalogue/pad/P65017NX' },
  fluid: { title: 'Brembo — การเลือกน้ำมันเบรกให้ตรงข้อกำหนดรถ', url: 'https://asia.bremboparts.com/america/en/support/car/how-to-choose-the-right-product/which-is-the-right-brake-fluid-for-my-car-195105' },
  teslaBrakes: { title: 'Tesla Model 3 — คู่มือภาษาไทย: เบรกและ Regenerative Braking', url: 'https://www.tesla.com/ownersmanual/model3/th_th/GUID-3DFFB071-C0F6-474D-8A45-17BE1A006365.html' },
  teslaSize: { title: 'Tesla Model 3 — คู่มือภาษาไทย: ขนาดจานเบรก', url: 'https://www.tesla.com/ownersmanual/model3/th_th/GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html' },
  teslaService: { title: 'Tesla Thailand — การบำรุงรักษารถ', url: 'https://www.tesla.com/th_th/support/vehicle-maintenance' },
  plaid: { title: 'Tesla — Model S Plaid Track Package (ตลาด UAE) และรายการอุปกรณ์', url: 'https://shop.tesla.com/en_ae/product/model-s-plaid-track-package' },
  inthanon: { title: 'ประชาสัมพันธ์จังหวัดเชียงใหม่ — สภาพเส้นทาง ทล.1009 จอมทอง–อินทนนท์', url: 'https://chiangmai.prd.go.th/th/content/category/detail/id/9/iid/227283' },
  thapBoek: { title: 'DASTA — เส้นทางหล่มเก่า–ภูทับเบิก ผ่าน ทล.2331', url: 'https://cbtthailand.dasta.or.th/webapp/relattraction/content/1118/' },
  evKit: { title: 'Brembo — EV Kit สำหรับการใช้งานเบรกของรถไฟฟ้า', url: 'https://www.brembo.com/en/solutions/for-your-car/ev-kit' },
  sss: { title: 'ENDLESS Japan — SSS', url: 'https://www.endless-sport.co.jp/products/brake_pad/SSS.html' },
  ssm: { title: 'ENDLESS Japan — SSM PLUS', url: 'https://www.endless-sport.co.jp/products/brake_pad/SSMPLUS.html' },
  mx72: { title: 'ENDLESS Japan — MX72', url: 'https://www.endless-sport.co.jp/products/brake_pad/MX72.html' },
  mx72Plus: { title: 'ENDLESS Japan — MX72 PLUS', url: 'https://www.endless-sport.co.jp/products/brake_pad/MX72PLUS.html' },
  endlessCaliper: { title: 'ENDLESS Japan — 6POT และรายละเอียดคาลิเปอร์', url: 'https://www.endless-sport.co.jp/products/brake_caliper/index_6POT.html' },
  endlessFitment: { title: 'ENDLESS Japan — ตารางรถสำหรับชุดคาลิเปอร์', url: 'https://www.endless-sport.co.jp/products/brake_caliper/car_list.html' },
  endlessCoating: { title: 'ENDLESS Japan — ข้อควรระวังสำหรับจานเคลือบกันสนิม', url: 'https://www.endless-sport.co.jp/products/brake_pad/caution_antiRust.html' },
  endlessCcm: { title: 'ENDLESS — ผ้าเบรกสำหรับจาน CCM', url: 'https://endless-brake.info/products/brake-pads/for-ccm-discs/' },
  projectMu: { title: 'Project μ Japan — TYPE PS', url: 'https://www.project-mu.co.jp/ja/product-info/type_ps' },
};
