export const evTyreArticle = {
  path: '/articles/ev-tyre-and-coilover-selection-guide',
  title: 'ยาง EV ต่างจากยางทั่วไปยังไง?',
  description: 'ดูว่ายาง EV ของ Michelin, Hankook, Continental และ Pirelli ออกแบบมาเพื่ออะไร มีข้อดีและข้อจำกัดยังไง เทียบกับ Michelin Pilot Sport 4 S ก่อนเลือกยางให้รถไฟฟ้า',
  publishedAt: '2026-08-27T08:00:00+07:00',
  updatedAt: '2026-09-29T08:00:00+07:00',
  readTime: '12 นาที',
  image: '/images/editorial/ev-tyres/ev-tyre-cover-desktop.png',
  imageAlt: 'ภาพปก EVSELECT ยางรถ EV ต่างจากยางทั่วไปยังไง พร้อมภาพประกอบรถไฟฟ้าและยาง',
  imageWidth: 1731,
  imageHeight: 909,
  mobileImage: '/images/editorial/ev-tyres/ev-tyre-cover.png',
  mobileImageWidth: 941,
  mobileImageHeight: 1672,
};

export const tyreSources = {
  eprimacy: 'https://www.michelin.co.th/auto/tyres/michelin-e-primacy',
  pilotEv: 'https://www.michelin.co.th/auto/tyres/michelin-pilot-sport-ev',
  pilotEvPress: 'https://michelinmedia.com/pages/blog/detail/article/c/a1046/',
  ps4s: 'https://www.michelin.co.th/auto/tyres/michelin-pilot-sport-4-s',
  hankook: 'https://www.hankooktire.com/us/en/tire/ion/evo.html',
  hankookPress: 'https://www.hankooktire-mediacenter.com/press-kits/messen/2024/the-tire-cologne-2024/press-release?cHash=b3b8e83e32da7fcdd8a9c1a099a36936&tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=11212',
  continental: 'https://www.continental-tires.com/products/car/tires/ecocontact-7/',
  continentalPress: 'https://www.continental.com/en/press/press-releases/20250205-ecocontact7/',
  pirelli: 'https://www.pirelli.com/tires/en-us/car/press-releases/pzero-e-230713',
  pirelliElect: 'https://www.pirelli.com/tyres/en-gb/car/catalogue/product/p-zero-e-elect',
  labels: 'https://energy-efficient-products.ec.europa.eu/product-list/tyres_en',
  parameters: 'https://energy-efficient-products.ec.europa.eu/product-list/tyres/how-read-tyre-parameters_en',
  load: 'https://www.michelin.co.th/auto/advice/ev-guide/high-load-capacity-tyres',
  acoustic: 'https://www.michelin.co.th/why-michelin/innovation/acoustic-technology',
  manual: 'https://www.tesla.com/ownersmanual/model3/th_th/GUID-FDDB10EF-FFA9-46EB-B8CC-03614AE92B6B.html',
  repair: 'https://www.michelin.co.th/auto/advice/change-tyres/tyre-repair',
  newMichelin: 'https://www.michelin.com/en/publications/products-and-services/new-michelin-primacy-5-energy-michelin-pilot-sport-5-energy',
  adac: 'https://www.adac.de/rund-ums-fahrzeug/ausstattung-technik-zubehoer/reifen/reifentest/sommerreifen/205-55-r16/michelin-eprimacy-id-4726/',
  tireRack: 'https://www.tirerack.com/tires/tests/are-ev-specific-tires-better-than-popular-non-ev-tires?ttid=327',
};

export const tyreModels = [
  {
    id: 'michelin-eprimacy', name: 'Michelin e.Primacy', direction: 'ให้ความสำคัญกับพลังงานและการใช้งานประจำวัน',
    image: '/images/editorial/ev-tyres/michelin-eprimacy-real.jpg', width: 2560, height: 1920,
    alt: 'ภาพถ่าย Michelin e.Primacy ขนาด 225/45 R21 บนล้อ Toyota Crown Crossover',
    caption: 'ภาพถ่าย e.Primacy ขนาด 225/45 R21 บน Toyota Crown Crossover ใช้แสดงยางรุ่นจริง ไม่ใช่ e.Primacy All Season หรือหลักฐานว่าสเปกนี้ใช้แทนรถไทยได้',
    credit: 'Michelin', source: tyreSources.eprimacy,
    imageSource: 'https://commons.wikimedia.org/wiki/File:The_tire_wheel_of_Toyota_CROWN_CROSSOVER_RS%22Advanced%22_(5AA-TZSH35-AETAT(F)).jpg',
    imageAuthor: 'Tokumeigakarinoaoshima',
    engineering: 'Michelin ใช้ Energy Passive Compound เพื่อลดพลังงานที่สูญเสียขณะเนื้อยางเปลี่ยนรูป ร่วมกับ Slim Belt หรือเข็มขัดรัดหน้ายางที่บางลง เป้าหมายคือทำให้ยางกลิ้งโดยใช้พลังงานน้อยลง พร้อมอายุใช้งานและความสบายสำหรับการขับทุกวัน',
    pro: 'โจทย์ชัดสำหรับคนที่อยากรักษาระยะวิ่งต่อชาร์จและไม่ได้ต้องการบุคลิกยางสปอร์ตจัด การลดแรงต้านการหมุนมีประโยชน์กับรถไฮบริดและรถเครื่องยนต์ด้วย จึงไม่ใช่คุณสมบัติที่มีประโยชน์กับ EV เท่านั้น',
    con: 'ถ้าให้ความสำคัญกับความไวของพวงมาลัยหรือการเข้าโค้งหนัก ๆ ต้องดูผลทดสอบด้านนั้นเพิ่ม ไม่ควรใช้คำว่าประหยัดไฟแทนคะแนนการควบคุม และตัวเลขประหยัดพลังงานในโฆษณาไม่ใช่อัตราที่รถทุกคันจะทำได้',
    fit: 'เหมาะจะเริ่มพิจารณาเมื่อเน้นเดินทางทุกวัน ความสบาย และพลังงาน; เปรียบเทียบเบรกเปียกของขนาดจริงก่อนตัดสินใจ',
  },
  {
    id: 'michelin-pilot-sport-ev', name: 'Michelin Pilot Sport EV', direction: 'สมรรถนะสำหรับ EV ที่ยังต้องคุมระยะวิ่งและเสียง',
    image: '/images/editorial/ev-tyres/michelin-ev-real.jpg', width: 2560, height: 1920,
    alt: 'ภาพถ่าย Michelin Pilot Sport EV บนล้อ Mercedes-AMG EQS 53 4MATIC+ เห็นชื่อรุ่นที่แก้มยาง',
    caption: 'ภาพถ่าย Pilot Sport EV บน Mercedes-AMG EQS 53 4MATIC+ ใช้ประกอบชื่อรุ่น ไม่ได้ยืนยันขนาด รหัส OE หรือสเปกยางของรถที่จำหน่ายในไทย',
    credit: 'Michelin', source: tyreSources.pilotEv,
    imageSource: 'https://commons.wikimedia.org/wiki/File:The_tire_wheel_of_Mercedes-AMG_EQS_53_4MATIC%2B_(ZAA-297155).jpg',
    imageAuthor: 'Tokumeigakarinoaoshima',
    engineering: 'รุ่นนี้วางโจทย์ต่างจาก e.Primacy: ต้องรองรับการขับแบบสปอร์ตของรถไฟฟ้าด้วย Michelin อธิบายว่า ElectricGrip Compound ใช้เนื้อยางส่วนกลางที่แข็งเพื่อรับมือแรงบิด ขณะเดียวกันลดแรงต้านการหมุน และใช้ Acoustic Technology ช่วยลดเสียงก้องในยาง',
    pro: 'เป็นตัวเลือกสำหรับคนที่ต้องการการควบคุมแบบสปอร์ต แต่ยังให้ความสำคัญกับเสียงและพลังงาน ไม่ได้ออกแบบโดยเอาระยะวิ่งออกจากสมการ',
    con: 'คำว่า Pilot Sport ไม่ได้ทำให้มันเป็น Pilot Sport 4 S ที่ใส่โฟมเพิ่ม และไม่ใช่หลักฐานว่ารุ่น EV จะเบรกหรือเข้าโค้งดีกว่า 4 S ทุกสภาพ คำกล่าวเรื่องระยะวิ่งเพิ่มของผู้ผลิตต้องอ่านคู่เทียบและเงื่อนไขให้ครบ',
    fit: 'เหมาะจะนำมาเทียบเมื่ออยากได้ยางแนวสปอร์ตสำหรับ EV โดยยังสนใจประสิทธิภาพพลังงาน; ตรวจรหัส OE และขนาดหน้า–หลังให้ตรงรถ',
  },
  {
    id: 'hankook-ion-evo', name: 'Hankook iON evo', direction: 'พยายามเก็บทั้งความเงียบ การสึก และการยึดเกาะไว้ด้วยกัน',
    image: '/images/editorial/ev-tyres/hankook-ion-evo.jpg', width: 8000, height: 6001,
    alt: 'ภาพผลิตภัณฑ์ Hankook iON evo พร้อมล้อ เห็นชื่อรุ่นบนแก้มยาง',
    caption: 'iON evo รุ่น Summer จากชุดภาพสื่อ Hankook; ฉากประกอบไม่ใช่ถนนไทย และไม่ใช่ภาพการทดสอบของเรา',
    credit: 'Hankook Tire', source: tyreSources.hankook, imageSource: tyreSources.hankookPress,
    engineering: 'Hankook แบ่งงานออกเป็นหลายส่วน: Sound Absorber จัดการเสียงก้อง, Opti Pitch จัดลำดับขนาดบล็อกดอกยางเพื่อลดเสียง, Round Even กระจายแรงกดในหน้าสัมผัส และ ProDurable Compound มุ่งเรื่องการสึก ส่วนบล็อกไหล่ยางกับร่องด้านข้างถูกออกแบบให้ทำงานร่วมกันด้านแรงขับและถนนเปียก',
    pro: 'แนวคิดครอบคลุมสิ่งที่คนใช้ EV เจอพร้อมกัน ทั้งเสียงที่ได้ยินชัดขึ้น แรงบิด และความต้องการประหยัดพลังงาน มีการปรับลายดอกยางร่วมกับวัสดุ ไม่ได้พึ่งโฟมเพียงชิ้นเดียว',
    con: 'ต้องแยก iON evo, iON evo SUV และ iON evo AS ให้ถูก รุ่น AS เป็น All Season; เอาผลทดสอบของชื่อใกล้กันมาใช้แทนกันไม่ได้ ส่วนฉลากระดับ A ก็ต้องตรวจขนาดและรหัสสินค้าที่จะซื้อ ไม่ใช่อ่านคำโฆษณารวมของตระกูลแล้วจบ',
    fit: 'เหมาะจะพิจารณาเมื่ออยากได้ยางที่พัฒนาโดยตั้งโจทย์ EV ตั้งแต่ต้น; แหล่งสเปกที่อ้างเป็นตลาดสหรัฐฯ จึงยังต้องตรวจรายการที่ขายและรับประกันในไทย',
  },
  {
    id: 'continental-ecocontact-7', name: 'Continental EcoContact 7', direction: 'ลดการสูญเสียทั้งในโครงยางและอากาศรอบแก้มยาง',
    image: '/images/editorial/ev-tyres/continental-ecocontact-7.jpg', width: 3000, height: 2250,
    alt: 'ภาพผลิตภัณฑ์ Continental EcoContact 7 และ EcoContact 7 S วางคู่กัน',
    caption: 'ภาพชุดเปิดตัว EcoContact 7 และ EcoContact 7 S จาก Continental ต้องแยกสองรุ่นนี้เมื่ออ่านสเปกหรือผลทดสอบ',
    credit: 'Continental AG', source: tyreSources.continentalPress, imageSource: tyreSources.continentalPress,
    engineering: 'Continental ใช้ Smart Energy Casing ลดการสูญเสียภายในโครงยาง ร่วมกับสูตร Green Chili 3.0 ส่วนรอยบุ๋ม Aerodimple บนแก้มยางมุ่งลดแรงต้านอากาศ และ Silent Pattern ปรับระยะกับมุมของบล็อกดอกยางเพื่อลดเสียงที่คนภายนอกรถได้ยินในเมือง',
    pro: 'แสดงให้เห็นว่ายางประหยัดพลังงานไม่ได้ปรับแค่เนื้อยาง และไม่จำเป็นต้องเป็นรุ่น EV-only ผู้ผลิตระบุว่าใช้ได้กับรถหลายระบบขับเคลื่อนเมื่อเลือกสเปกตรงรถ',
    con: 'EcoContact 7 เน้นแรงต้านการหมุนต่ำ ส่วน 7 S ปรับสูตรเพื่อการควบคุมและการยึดเกาะมากขึ้น จึงห้ามรวมเป็นยางเส้นเดียวกัน อีกทั้งคำกล่าวเรื่องเสียงภายนอกที่ความเร็วในเมืองไม่ได้ยืนยันความเงียบในห้องโดยสารบนทางด่วน',
    fit: 'เหมาะจะพิจารณาเมื่อให้ความสำคัญกับพลังงานเป็นหลัก; ข้อมูลนี้อ้างรุ่นเปิดตัวสากล ไม่ยืนยันว่าทุกขนาดมีจำหน่ายในไทย',
  },
  {
    id: 'pirelli-p-zero-e', name: 'Pirelli P Zero E', direction: 'ยาง UHP ที่เอาประสิทธิภาพพลังงานมาเป็นโจทย์ร่วม',
    image: '/images/editorial/ev-tyres/pirelli-p-zero-e.jpg', width: 2000, height: 2000,
    alt: 'ภาพผลิตภัณฑ์ Pirelli P Zero E เห็นชื่อรุ่นและเครื่องหมาย Elect',
    caption: 'P Zero E จากชุดภาพเปิดตัวของ Pirelli เห็นเครื่องหมาย Elect บนแก้มยาง; ไม่ใช่ P Zero PZ4 หรือ P Zero PZ5',
    credit: 'Pirelli', source: tyreSources.pirelli, imageSource: tyreSources.pirelli,
    engineering: 'Pirelli วาง P Zero E เป็นยาง Ultra High Performance หรือ UHP สำหรับรถไฟฟ้า ผสานเทคโนโลยี Elect เพื่อตอบโจทย์น้ำหนัก แรงบิด เสียง และแรงต้านการหมุน พร้อม RunForward ซึ่งช่วยให้เคลื่อนรถต่อได้ในเงื่อนไขที่กำหนดหลังสูญเสียแรงดัน',
    pro: 'เป็นอีกตัวอย่างว่าคำว่า EV กับ Performance อยู่ในยางรุ่นเดียวกันได้ ผู้ผลิตระบุฉลาก EU ระดับ A ทั้งสามด้านในชุดขนาดช่วงเปิดตัวปี 2023 จึงวางตำแหน่งให้คุมพลังงานพร้อมกับสมรรถนะถนน',
    con: 'Triple A ไม่ใช่ผลชนะ Pilot Sport 4 S ในการทดสอบแบบตัวต่อตัว และไม่ได้ครอบคลุมทุกมิติ เช่น ความไวพวงมาลัยหรือการเหินน้ำ ส่วน RunForward ไม่ใช่การอนุญาตให้ขับต่อหลังยางเสียหายทุกรูปแบบ ต้องทำตามเงื่อนไขของยางและรถ',
    fit: 'เหมาะจะนำมาเทียบเมื่ออยากได้ยางแนว UHP ที่คำนึงถึงพลังงานด้วย; ตรวจ Elect, RunForward, รหัส OE และขนาดที่จำหน่ายจริงในไทยแยกกัน',
  },
  {
    id: 'michelin-pilot-sport-4-s', name: 'Michelin Pilot Sport 4 S', direction: 'ยาง Performance ที่เริ่มจากการควบคุมและการยึดเกาะ',
    image: '/images/editorial/ev-tyres/michelin-ps4s-real.jpg', width: 3024, height: 3024,
    alt: 'ภาพถ่าย Michelin Pilot Sport 4 S บนล้อ Cadillac เห็นชื่อรุ่นและขนาด 295/30 ZR19 บนแก้มยาง',
    caption: 'ภาพถ่าย Pilot Sport 4 S บนล้อ Cadillac ขนาด 295/30 ZR19 เป็นภาพประกอบรุ่น ไม่ใช่ยางขนาดเดียวกับผลทดสอบด้านล่าง และไม่ใช่ Pilot Sport 4, 4 SUV หรือ All Season 4',
    credit: 'Michelin', source: tyreSources.ps4s,
    imageSource: 'https://commons.wikimedia.org/wiki/File:Cadillac_Wheel_with_Michelin_Pilot_Sport_4_S_Tire.jpg',
    imageAuthor: 'TaurusEmerald',
    engineering: 'Pilot Sport 4 S เน้นการตอบสนองและการรักษาหน้าสัมผัสขณะขับแบบสปอร์ต ด้วย Dynamic Response ร่วมกับ Bi-Compound ที่แยกหน้าที่เนื้อยางด้านในและด้านนอก โดย Michelin ระบุว่า Bi-Compound มีข้อยกเว้นในบางขนาด รุ่นนี้ออกแบบสำหรับถนนและการลงสนามเป็นครั้งคราว',
    pro: 'โจทย์ตรงกับคนที่ให้ความสำคัญกับพวงมาลัย การเข้าโค้ง และการยึดเกาะบนถนนแห้ง–เปียก เว็บไซต์ Michelin ไทยระบุว่ารองรับรถไฟฟ้าด้วย จึงไม่ควรตัดออกจากตัวเลือกเพียงเพราะชื่อรุ่นไม่มีคำว่า EV',
    con: 'ไม่ได้วางจุดขายหลักไว้ที่แรงต้านการหมุนต่ำสุด หากเปลี่ยนจากยางประหยัดพลังงานต้องประเมินระยะวิ่ง เสียง และความสบายร่วมด้วย แต่ยังสรุปเป็นเปอร์เซ็นต์กินไฟเพิ่มหรือรับรองว่าดังกว่าไม่ได้หากไม่มีผลเทียบในเงื่อนไขเดียวกัน',
    fit: 'เหมาะจะพิจารณาเมื่อการควบคุมสำคัญกว่าการไล่ระยะวิ่งให้มากที่สุด โดยขนาด พิกัดรับน้ำหนัก พิกัดความเร็ว และล้อผ่านข้อกำหนดของรถก่อน',
  },
] as const;
