import Link from 'next/link';
import InformationPage, { informationLinkStyle } from '@/components/InformationPage';
import { CookieSettingsButton } from '@/components/CookieConsent';
import { getAnalyticsMeasurementId } from '@/lib/analytics';
import BrandHomeLink from '@/components/BrandHomeLink';

export const metadata = {
  alternates: { canonical: '/privacy' },
  robots: { index: true, follow: true },
  title: 'นโยบายความเป็นส่วนตัว | EVSELECT',
  description: 'การใช้ข้อมูลบนเว็บไซต์ EVSELECT คุกกี้ การวิเคราะห์การใช้งาน และวิธีเปลี่ยนหรือถอนความยินยอม',
};

export default function PrivacyPage() {
  const analyticsConfigured = Boolean(getAnalyticsMeasurementId({ NODE_ENV: process.env.NODE_ENV, VERCEL_ENV: process.env.VERCEL_ENV, GA4_MEASUREMENT_ID: process.env.GA4_MEASUREMENT_ID }));
  return <InformationPage title="นโยบายความเป็นส่วนตัว" intro={<>หน้านี้อธิบายว่า <BrandHomeLink /> ใช้ข้อมูลจากการเข้าชม <Link href="/" className={informationLinkStyle}>evselects.com</Link> อย่างไร คุณเลือกปฏิเสธการวิเคราะห์ได้ และยังอ่านบทความหรือติดต่อทีมงานได้ตามปกติ</>}>
    <p className="text-sm text-slate-500">ปรับปรุงล่าสุด: 1 ตุลาคม 2569</p>
    <section className="space-y-3"><h2 className="text-2xl font-bold text-slate-900">เว็บไซต์นี้และช่องทางติดต่อ</h2><p><BrandHomeLink /> ดูแลเว็บไซต์นี้เพื่อเผยแพร่บทความรถยนต์ไฟฟ้า ความรู้เรื่องอุปกรณ์ และข่าวการเปิดตัวสินค้า ขณะนี้ยังไม่เปิดรับคำสั่งซื้อหรือชำระเงินบนเว็บไซต์</p><p>หากมีคำถามเกี่ยวกับข้อมูลส่วนบุคคล ให้ใช้ <Link href="/contact" className={informationLinkStyle}>ช่องทางติดต่อทีมงาน</Link> เพื่อเปิดแชทกับเพจ <Link href="/" className={informationLinkStyle}>EVSELECTS</Link> ทาง Facebook โปรดระบุเรื่องที่ต้องการให้ตรวจสอบ โดยไม่ส่งรหัสผ่านหรือข้อมูลบัตรชำระเงิน</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold text-slate-900">ข้อมูลจากการเปิดเว็บไซต์</h2><p>การแสดงหน้าเว็บต้องส่งข้อมูลทางเทคนิค เช่น IP address ประเภทเบราว์เซอร์ และคำขอเปิดหน้าเว็บ ไปยังผู้ให้บริการโฮสต์ Vercel เพื่อส่งเนื้อหาและดูแลการทำงานของเว็บไซต์ ข้อมูลส่วนนี้แยกจาก Google Analytics และไม่ถูกปิดด้วยปุ่มปฏิเสธการวิเคราะห์</p><p>เว็บไซต์บันทึกตัวเลือกความยินยอมและเวลาที่เลือกไว้ใน local storage ของเบราว์เซอร์ โดยขอให้เลือกใหม่เมื่อครบ 180 วันหรือเมื่อข้อมูลนี้ถูกล้าง การบันทึกตัวเลือกไม่ได้ใช้ติดตามการอ่านบทความ</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold text-slate-900">การวิเคราะห์ด้วย Google Analytics 4</h2><p>{analyticsConfigured ? 'เว็บไซต์ตั้งค่า Google Analytics 4 แล้ว แต่จะโหลดและเริ่มวิเคราะห์เมื่อคุณอนุญาตเท่านั้น' : 'ขณะนี้เว็บไซต์ยังไม่ได้เปิดใช้งาน Google Analytics 4 เมื่อเปิดใช้งานแล้ว จะโหลดและเริ่มวิเคราะห์เมื่อคุณอนุญาตเท่านั้น'} หากยังไม่เลือกหรือปฏิเสธ เว็บไซต์จะไม่โหลดแท็ก Google Analytics และไม่ส่งข้อมูลการใช้งานให้บริการนี้</p><p>เมื่ออนุญาต เราใช้ข้อมูลหน้าที่เปิด แหล่งที่มาของการเข้าชม ประเภทอุปกรณ์ ระยะเวลาที่ใช้งาน การเลื่อนหน้า และการคลิกลิงก์ เพื่อดูว่าบทความไหนมีประโยชน์และปรับปรุงเว็บไซต์ การคลิกไป Messenger หรือ Shopee เป็นเพียงความสนใจติดต่อหรือซื้อสินค้า ไม่ใช่หลักฐานว่าได้ส่งข้อความหรือซื้อแล้ว</p><p>เราไม่ส่งชื่อ อีเมล หมายเลขโทรศัพท์ รหัสผ่าน หรือข้อความที่กรอกในฟอร์มเป็นข้อมูลวิเคราะห์ และไม่เปิดใช้ Google signals หรือการปรับโฆษณาให้ตรงกับบุคคลในชุดติดตามนี้</p><p>คุกกี้ Google Analytics ของเว็บไซต์ใช้ชื่อขึ้นต้นด้วย <code className="rounded bg-slate-100 px-1.5 text-sm">evselect_ga</code> และตั้งอายุไว้ไม่เกิน 180 วัน ข้อมูลความยินยอมถูกเก็บในเบราว์เซอร์ ไม่ใช่บัญชีผู้ใช้</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold text-slate-900">เปลี่ยนใจหรือถอนความยินยอม</h2><p>กด <CookieSettingsButton className={informationLinkStyle} /> ที่หน้านี้หรือท้ายหน้าเว็บ แล้วปิด “การวิเคราะห์การใช้งาน” และบันทึกการตั้งค่า หากเริ่มวิเคราะห์ไปแล้ว หน้าจะโหลดใหม่เพื่อหยุดแท็กและลบคุกกี้วิเคราะห์ของเว็บไซต์ การถอนความยินยอมมีผลกับการเก็บข้อมูลหลังจากนั้น และไม่ได้ลบข้อมูลที่ส่งไปก่อนหน้านี้โดยอัตโนมัติ</p><p>คุณล้างคุกกี้และข้อมูลเว็บไซต์ผ่านการตั้งค่าเบราว์เซอร์ได้ด้วย หลังล้างข้อมูล เราจะถามตัวเลือกอีกครั้ง</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold text-slate-900">ผู้ให้บริการภายนอกและรายงาน</h2><p>ข้อมูลวิเคราะห์ที่คุณอนุญาตจะประมวลผลโดย Google และอาจถูกประมวลผลนอกประเทศไทย หากเชื่อมต่อ Supermetrics เราจะใช้บริการนี้ดึงรายงานจาก GA4 เช่น แหล่งที่มาของผู้อ่าน บทความยอดนิยม และจำนวนคลิก เพื่อช่วยวิเคราะห์ภาพรวม Supermetrics ไม่ใช่แท็กติดตามเพิ่มเติมบนหน้าเว็บ</p><p>อ่าน <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className={informationLinkStyle}>นโยบายความเป็นส่วนตัวของ Google<span className="sr-only"> (เปิดแท็บใหม่)</span></a>, <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className={informationLinkStyle}>นโยบายของ Vercel<span className="sr-only"> (เปิดแท็บใหม่)</span></a> และ <a href="https://supermetrics.com/privacy-policy" target="_blank" rel="noopener noreferrer" className={informationLinkStyle}>นโยบายของ Supermetrics<span className="sr-only"> (เปิดแท็บใหม่)</span></a> เพื่อดูรายละเอียดของแต่ละบริการ</p><p>เมื่อเปิดลิงก์ไป Facebook, Messenger, Shopee หรือเว็บไซต์อื่น นโยบายของผู้ให้บริการปลายทางจะใช้กับการใช้งานที่นั่น หากส่งข้อความถึงเรา เราจะใช้ข้อมูลที่ส่งมาเพื่อตอบคำถามหรือตรวจสอบเรื่องที่แจ้ง โดยไม่ส่งเนื้อหาแชทเข้า Google Analytics</p></section>
    <section className="space-y-3"><h2 className="text-2xl font-bold text-slate-900">สอบถามหรือขอจัดการข้อมูล</h2><p>ติดต่อทีมงานเพื่อสอบถามข้อมูลที่เกี่ยวข้องกับคุณ ขอเข้าถึง แก้ไข ลบ หรือแจ้งข้อกังวลเกี่ยวกับการใช้ข้อมูลได้ เราจะตรวจสอบคำขอและสิ่งที่สามารถระบุได้จากข้อมูลที่มี การวิเคราะห์เว็บไซต์ไม่ได้ผูกกับชื่อหรือบัญชีของคุณ จึงอาจระบุรายการเข้าชมเฉพาะบุคคลไม่ได้จากชื่อหรืออีเมลเพียงอย่างเดียว</p><p>หากมีการเปลี่ยนผู้ให้บริการหรือวิธีใช้ข้อมูล เราจะปรับปรุงหน้านี้และวันที่ด้านบน การใช้ข้อมูลเพื่อวัตถุประสงค์เพิ่มเติมจะไม่ถือว่าคุณอนุญาตไว้แล้วจากตัวเลือกการวิเคราะห์นี้</p></section>
  </InformationPage>;
}
